language: rust
os:
  - windows
  - linux
rust:
  - stable
script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/release/rconcmd
  draft: true
  on:
    tags: true
