language: rust
os:
  - windows
  - linux
rust:
  - stable
script:
  # On regular test
  - if [ -z "$TRAVIS_TAG" ]; cargo build --verbose --all; fi
  - if [ -z "$TRAVIS_TAG" ]; cargo test --verbose --all; fi
  # On deploy
  - if [ -n "$TRAVIS_TAG" ]; cargo test --release --verbose --all; fi
  - if [ -n "$TRAVIS_TAG" ]; cargo build --release --verbose --all; fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/release/rconcmd
  draft: true
  on:
    tags: true
