version: 0.0.{build}
os:
  - Visual Studio 2017
clone_depth: 1
configuration:
  - Debug
platform:
  - Win32
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.36.0

build_script: appveyor.bat
